### ISSUE TITLE
Extension doens't work. Accounts page empty, no controls, error in console.

### ISSUE THREAD

**Issue by maxgrass** [3axap4eHko/OWA-Notifier#82]
v 4.0.0.5
```
Uncaught (in promise) TypeError: Cannot read property 'match' of undefined
    at Object.c.urlParse (eval at <anonymous> (chrome-extension://hldldpjjjagjfikfknadmnnmpbbhgihg/js/browser.min.js:4:29345), <anonymous>:124:14)
    at render (eval at <anonymous> (chrome-extension://hldldpjjjagjfikfknadmnnmpbbhgihg/js/browser.min.js:4:29345), <anonymous>:73:17)
    at y._renderValidatedComponentWithoutOwnerOrContext (chrome-extension://hldldpjjjagjfikfknadmnnmpbbhgihg/js/react.min.js:13:14721)
    at y._renderValidatedComponent (chrome-extension://hldldpjjjagjfikfknadmnnmpbbhgihg/js/react.min.js:13:14809)
    at y.mountComponent (chrome-extension://hldldpjjjagjfikfknadmnnmpbbhgihg/js/react.min.js:13:11111)
    at Object.a.mountComponent (chrome-extension://hldldpjjjagjfikfknadmnnmpbbhgihg/js/react.min.js:14:31634)
    at m.y.Mixin.mountChildren (chrome-extension://hldldpjjjagjfikfknadmnnmpbbhgihg/js/react.min.js:14:23220)
    at m.Mixin._createContentMarkup (chrome-extension://hldldpjjjagjfikfknadmnnmpbbhgihg/js/react.min.js:13:22000)
    at m.Mixin.mountComponent (chrome-extension://hldldpjjjagjfikfknadmnnmpbbhgihg/js/react.min.js:13:20957)
    at Object.a.mountComponent (chrome-extension://hldldpjjjagjfikfknadmnnmpbbhgihg/js/react.min.js:14:31634)
```

**Comment by 3axap4eHko** [comment]
Where did you get this message?

**Comment by maxgrass** [comment]
chrome-extension://hldldpjjjagjfikfknadmnnmpbbhgihg/options.html#settings-general
chrome 49 x64
I've been clicking between Tabs "General" and "Accounts" like 5 times.
```
yyf-core.min.js:2 Uncaught (in promise) TypeError: Cannot read property 'match' of undefined(…)c.urlParse @ yyf-core.min.js:2render @ settings-accounts.js:1y._renderValidatedComponentWithoutOwnerOrContext @ react.min.js:13y._renderValidatedComponent @ react.min.js:13y.mountComponent @ react.min.js:13a.mountComponent @ react.min.js:14y.Mixin.mountChildren @ react.min.js:14m.Mixin._createContentMarkup @ react.min.js:13m.Mixin.mountComponent @ react.min.js:13a.mountComponent @ react.min.js:14y.Mixin.mountChildren @ react.min.js:14m.Mixin._createContentMarkup @ react.min.js:13m.Mixin.mountComponent @ react.min.js:13a.mountComponent @ react.min.js:14y.Mixin.mountChildren @ react.min.js:14m.Mixin._createContentMarkup @ react.min.js:13m.Mixin.mountComponent @ react.min.js:13a.mountComponent @ react.min.js:14y.mountComponent @ react.min.js:13a.mountComponent @ react.min.js:14y.mountComponent @ react.min.js:13a.mountComponent @ react.min.js:14v @ react.min.js:14o.perform @ react.min.js:15m @ react.min.js:14o.perform @ react.min.js:15d.batchedUpdates @ react.min.js:14a @ react.min.js:15Q._renderNewRootComponent @ react.min.js:14Q._renderSubtreeIntoContainer @ react.min.js:14Q.render @ react.min.js:14(anonymous function) @ settings-accounts.js:1Promise.resolve (async)messageListener @ extensions::messaging:346EventImpl.dispatchToListener @ extensions::event_bindings:387publicClass.(anonymous function) @ extensions::utils:94EventImpl.dispatch_ @ extensions::event_bindings:371EventImpl.dispatch @ extensions::event_bindings:393publicClass.(anonymous function) @ extensions::utils:94dispatchOnMessage @ extensions::messaging:310
```

**Comment by maxgrass** [comment]
Not sure, but the options' page looks weird as well:
![2016-01-12 11_18_19-owa notifier - options](https://cloud.githubusercontent.com/assets/169885/12260904/37988dc0-b91e-11e5-83bc-ca6bb41a3fd4.png)

**Comment by 3axap4eHko** [comment]
Try to reinstall application

**Comment by maxgrass** [comment]
Yep. Solved by reinstalling, pbl corrupted db or ressources.
